[package]
name = "petunia-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
petunia-data.workspace = true

dirs.workspace = true
futures.workspace = true
gpui.workspace = true
gpui-component.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
filetime.workspace = true
tempfile.workspace = true
